---
# module: rd-ansible-squid-install/tasks/configure
# description: Configure rd-ansible-squid-install

- name: "Create a squid configuration in {{ squid_path }}"
  template:
    src: squid.conf.j2
    dest: "{{ squid_path }}"
    owner: root
    mode: 0644
  notify: restart_squid

- name: Create digest auth credentials
  template:
    src: passwd_digest.j2
    dest: "{{ squid_digest_path }}"
    owner: root
    mode:
  notify: restart_squid
  when: squid_auth_digests | length > 0

- name: Flush handlers so we can make sure Squid is enabled
  meta: flush_handlers

- name: Enable Squid - using command since the service and systemd command appear to not work correctly
  command: systemctl enable squid
  changed_when: false
